bgp: Add a knob to disable OSS in the enterprise script test
We will start a large refactoring that separates OSS and CEE BGP CPlane
entirely and make it possible to run CEE BGP CPlane with
`--enable-bgp-control-plane=false`.

During this refactoring we will use script tests to detect regression.
At any point in refactoring, we must not break the case that both OSS
and CEE are enabled.

This commit introduces a flag for the enterprise script test suite to
disable OSS BGP CPlane. By executing script tests with this flag, we can
test the case that only CEE BGP CPlane is enabled.

All tests are failing at this point with the flag:

```
$ PRIVILEGED_TESTS=1 go test -exec="sudo -E" ./enterprise/pkg/bgpv1/test/... -v -disable-oss-bgp-control-plane

<...>

--- FAIL: TestPrivilegedScript (0.20s)
    --- FAIL: TestPrivilegedScript/commands.txtar (30.88s)
    --- FAIL: TestPrivilegedScript/svc-sharing.txtar (30.90s)
    --- FAIL: TestPrivilegedScript/svc-traffic-policy.txtar (30.95s)
    --- FAIL: TestPrivilegedScript/pod-cidr.txtar (31.02s)
    --- FAIL: TestPrivilegedScript/svc-path-attributes.txtar (29.13s)
    --- FAIL: TestPrivilegedScript/svc-modifications.txtar (29.06s)
    --- FAIL: TestPrivilegedScript/svc-no-endpoints.txtar (29.11s)
    --- FAIL: TestPrivilegedScript/svc-kpr-disabled.txtar (28.99s)
    --- FAIL: TestPrivilegedScript/svc-adverts.txtar (0.09s)
    --- FAIL: TestPrivilegedScript/svc-aggregation.txtar (0.09s)
    --- FAIL: TestPrivilegedScript/route-import.txtar (0.09s)
    --- FAIL: TestPrivilegedScript/svc-gateway-proxy-redirect.txtar (0.10s)
    --- FAIL: TestPrivilegedScript/route-import-wildcard.txtar (0.04s)
    --- FAIL: TestPrivilegedScript/route-import-unnumbered.txtar (0.04s)
    --- FAIL: TestPrivilegedScript/pod-ip-pool.txtar (0.04s)
    --- FAIL: TestPrivilegedScript/route-import-multipath.txtar (0.04s)
    --- FAIL: TestPrivilegedScript/evpn-route-import.txtar (0.02s)
    --- FAIL: TestPrivilegedScript/peering-multi-instance.txtar (0.02s)
    --- FAIL: TestPrivilegedScript/peering-changes.txtar (0.02s)
    --- FAIL: TestPrivilegedScript/peering-default-gateway.txtar (0.05s)
    --- FAIL: TestPrivilegedScript/interface.txtar (0.03s)
    --- FAIL: TestPrivilegedScript/peering-ipv6.txtar (0.06s)
    --- FAIL: TestPrivilegedScript/peering-auth.txtar (0.05s)
    --- FAIL: TestPrivilegedScript/ent-rr-rr-advertisement.txtar (0.01s)
    --- FAIL: TestPrivilegedScript/ent-unnumbered.txtar (0.01s)
    --- FAIL: TestPrivilegedScript/ent-node-maintenance.txtar (0.01s)
    --- FAIL: TestPrivilegedScript/evpn-route-import-error-path.txtar (0.02s)
    --- FAIL: TestPrivilegedScript/ent-svc-health-checking.txtar (0.02s)
    --- FAIL: TestPrivilegedScript/ent-privnet-evpn.txtar (0.01s)
    --- FAIL: TestPrivilegedScript/ent-egw-adverts.txtar (0.01s)
```

Signed-off-by: Yutaro Hayakawa <yutaro.hayakawa@isovalent.com>